# Request
std_msgs/Header header  
MoveReq[] requests

---
# Result
int32 error_code        # error code
int32 SUCCESSFUL = 0
int32 UNSUCCESSFUL = -1

string error_str        # error message
---
# Feedback
string status           # status of the move
