## header 
std_msgs/Header header  

MoveReq[] instructions # list of instructions
---
# result
int32 error_code # status code

###
# error code Enum
###
int32 SUCCESSFUL = 0
int32 INVALID_GOAL = -1

string error_str # error message
---
# feedback

string status # status of the move
int32 move_index # i-th instruction index executed
string move_type # i-th move_type executed
